package adapter

import (
	"fmt"
	"os"
	"reflect"
	"strings"
)

// ------------------------------------------------------------
// DTO generation config
// ------------------------------------------------------------
type DTORequest struct {
	StructType interface{}
	DTOName    string
}

type DTOGenConfig struct {
	OutFile     string
	PackageName string
	Items       []DTORequest
}

// ------------------------------------------------------------
// Entry point
// ------------------------------------------------------------
func GenerateDTOFile(cfg DTOGenConfig) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by DTO generator. DO NOT EDIT.\n")
	sb.WriteString("package " + cfg.PackageName + "\n\n")

	imports := map[string]string{}
	generated := map[reflect.Type]string{}

	for _, item := range cfg.Items {
		generateDTORecursive(&sb, reflect.TypeOf(item.StructType), item.DTOName, cfg.PackageName, imports, generated)
	}

	// TODO: write imports if necessary (currently unused)

	return os.WriteFile(cfg.OutFile, []byte(sb.String()), 0644)
}

// ------------------------------------------------------------
// Recursive DTO generation
// ------------------------------------------------------------
func generateDTORecursive(sb *strings.Builder, t reflect.Type, dtoName, currentPkg string, imports map[string]string, generated map[reflect.Type]string) string {
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	// Already generated
	if existing, ok := generated[t]; ok {
		return existing
	}
	generated[t] = dtoName

	var fields []string
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)

		// Skip unexported or internal protobuf fields
		if f.PkgPath != "" || f.Name == "state" || f.Name == "sizeCache" || f.Name == "unknownFields" {
			continue
		}

		fieldType := resolveDTOField(f, sb, currentPkg, imports, generated)
		jsonName := toJSONName(f.Name)
		fields = append(fields, fmt.Sprintf("    %s %s `json:\"%s\"`", f.Name, fieldType, jsonName))
	}

	sb.WriteString(fmt.Sprintf("type %s struct {\n", dtoName))
	sb.WriteString(strings.Join(fields, "\n"))
	sb.WriteString("\n}\n\n")

	return dtoName
}

// ------------------------------------------------------------
// Resolve individual field type
// ------------------------------------------------------------
func resolveDTOField(f reflect.StructField, sb *strings.Builder, currentPkg string, imports map[string]string, generated map[reflect.Type]string) string {
	ft := f.Type

	isPtr := false
	for ft.Kind() == reflect.Ptr {
		isPtr = true
		ft = ft.Elem()
	}

	switch ft.Kind() {
	case reflect.Struct:
		if ft.PkgPath() == "" && ft.Name() == "Time" {
			if isPtr {
				return "*string"
			}
			return "string"
		}

		dtoName := ft.Name() + "Dto"
		generateDTORecursive(sb, ft, dtoName, currentPkg, imports, generated)

		if isPtr {
			return "*" + dtoName
		}
		return dtoName
	case reflect.Slice:
		elem := ft.Elem()
		// preserve pointer info for slice element
		elemField := reflect.StructField{Type: elem}
		return "[]" + resolveDTOField(elemField, sb, currentPkg, imports, generated)
	case reflect.Int, reflect.Int32, reflect.Int64:
		if ft.PkgPath() != "" {
			return "int"
		}
		return ft.Name()
	default:
		if isPtr {
			return "*" + ft.String()
		}
		return ft.String()
	}
}

// ------------------------------------------------------------
// Helpers
// ------------------------------------------------------------
func toJSONName(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToLower(name[:1]) + name[1:]
}
